class UpdateTrackingLine ():
	def __init__ (self):
		self.databaseName:str = None
		self.branch:str = None
		self.datetime:str = None
		self.batchId:str = None
		self.operation:str = None
		self.version:str = None
		self.result:str = None
